### ISSUE TITLE
Testing modules

### ISSUE THREAD

**Issue by jamebs** [NeuroSYS-pl/magda#12]
### What?
We would like to create a pattern for testing modules (real ones with business logic). However, it's impractical to mock module's internal methods (like `build`) or wrap into a complete pipeline. So, we need a new class - `ModuleTestingWrapper`.

### Why?
To give a reliable way for unit-testing real modules with a minimal baseline.

### How?
By creating a new module `magda.testing` with all testing-related classes and mocks. The `ModuleTestingWrapper` should behave like minimal SequentialPipeline i.e. without graphs, checking dependencies etc. because it'll always wrap only one module. However, it should support building modules and its whole life-cycle (bootstrap-run-teardown, even if they're mocked).

The example code:
```py
@accept(RawData)
@produce(ProcessedData)
@finalize
class MyModule(Module.Runtime):
    def bootstrap(self, **kwargs):
        self.do_something_with(self.parameters)

    def run(self, data: Module.ResultSet, **kwargs):
        return ProcessedData(data.get(RawData)[::-1])
```
```py
from magda.testing import ModuleTestingWrapper

async def test_should_not_compile():
    module = MyModule('my-module-a').set_parameters({}) # Missing required params

    with pytest.raises(Exception):
        await ModuleTestingWrapper(module).build() # it mimics pipeline.build()

async def test_should_process_correctly():
    module = MyModule('my-module-a').set_parameters(...)
    mock = await ModuleTestingWrapper(module).build()

    result = await mock.run(RawData('xyz'))
    assert result == ProcessedData('zyx'))
```

**Comment by lukaszsus** [comment]
I think you didn't cover the use case in which the module takes `request` argument. We need to specify how to handle this use case.

**Comment by jamebs** [comment]
Good point :+1: 

So we need to modify `mock.run` method. How about this?

`ModuleTestingWrapper(module).build()` returns a object, which supports 3 methods:
- `request(...)` for setting up the *request* object
- `data(...)` for setting up input(s) for a module
- `run(...)` to execute test-run.
 
**Example:**
```py
async def test_should_process_correctly():
    module = MyModule('my-module-a').set_parameters(...)
    mock = await ModuleTestingWrapper(module).build()

    # data only run
    result = await mock.data(RawData('xyz')).run()

    # multiple inputs
    result = await mock.data(
        RawData('xyz'),
        RawData('123'),
    ).run()

    # request + data only run
    result = await mock.request(10).data(RawData('xyz')).run()

    # plain run
    result = await mock.run()

    assert result == ProcessedData('zyx'))
```

You can remove `run` by overriding `__await__()` method of `mock` object. Then `await` will invoke the test-run with the current preset (data/request).

**Comment by lukaszsus** [comment]
Looks good for me :slightly_smiling_face:
